apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: argo-promotion-test-prod-us-central
  name: production-use2
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    version: v1.0.116
  labels:
    app.kubernetes.io/instance: argo-promotion-test-prod-us-central
  name: canary-demo
  namespace: production-use2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    version: v1.0.116
  labels:
    app.kubernetes.io/instance: argo-promotion-test-prod-us-central
  name: canary-demo-preview
  namespace: production-use2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    version: v1.0.116
  labels:
    app.kubernetes.io/instance: argo-promotion-test-prod-us-central
    db-schema: v1.11
    environment: production
  name: canary-demo
  namespace: production-use2
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
        - setWeight: 20
        - pause:
            duration: 5
        - setWeight: 80
        - pause:
            duration: 5
  template:
    metadata:
      annotations:
        version: v1.0.116
      labels:
        app: canary-demo
        environment: production
    spec:
      containers:
        - image: argoproj/rollouts-demo:green
          imagePullPolicy: Always
          name: canary-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    version: v1.0.116
  labels:
    app.kubernetes.io/instance: argo-promotion-test-prod-us-central
  name: canary-demo
  namespace: production-use2
spec:
  rules:
    - host: canary.dev.argoproj.io
      http:
        paths:
          - backend:
              service:
                name: canary-demo
                port:
                  name: http
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    version: v1.0.116
  labels:
    app.kubernetes.io/instance: argo-promotion-test-prod-us-central
  name: canary-demo-preview
  namespace: production-use2
spec:
  rules:
    - host: canary-preview.dev.argoproj.io
      http:
        paths:
          - backend:
              service:
                name: canary-demo-preview
                port:
                  name: http
            path: /
            pathType: Prefix
