apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: development-vc
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    version: v1.0.120
  labels:
    app.kubernetes.io/instance: development-vc
  name: canary-demo
  namespace: dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    version: v1.0.120
  labels:
    app.kubernetes.io/instance: development-vc
  name: canary-demo-preview
  namespace: dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    version: v1.0.120
  labels:
    app.kubernetes.io/instance: development-vc
    environment: development
  name: canary-demo
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
        - setWeight: 20
        - pause:
            duration: 5
        - setWeight: 80
        - pause:
            duration: 5
  template:
    metadata:
      annotations:
        version: v1.0.120
      labels:
        app: canary-demo
        environment: development
    spec:
      containers:
        - image: argoproj/rollouts-demo:yellow
          imagePullPolicy: Always
          name: canary-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
