apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-vc
  namespace: argocd
  labels:
    app: argo-promotion-test
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sourceHydrator:
    drySource:
      path: envs/prod-us-central
      repoURL: https://github.com/lloydsmithjr03/argo-promotion-test.git
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environments/prod-us-central-next
    syncSource:
      path: .
      targetBranch: environments/prod-us-central
  syncPolicy:
    automated: {}
