apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-promotion-test-promotion-strategy
  namespace: argocd
spec:
  ignoreDifferences:
  - group: promoter.argoproj.io
    kind: CommitStatus
    jsonPointers:
    - /spec/sha
    - /metadata/annotations/hcapActive
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: promotion
    repoURL: https://github.com/lloydsmithjr03/argo-promotion-test.git
    targetRevision: HEAD
