apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: argocdcommitstatus-sample
  namespace: default
spec:
  promotionStrategyRef:
    name: argocon-demo
  applicationSelector:
    matchLabels:
      app.kubernetes.io/name: argo-promotion-test