apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  annotations:
    hcapActive: "false"
  labels:
    promoter.argoproj.io/commit-status: hcap
  name: hcap
  namespace: argocd
spec:
  description: HCAP check for production
  gitRepositoryRef:
    name: git-repository-argo-promotion-test
  name: production/hcap
  sha: ""
  url: https://example.com