apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  annotations:
  name: argocon-demo
  namespace: argocd
spec:
  activeCommitStatuses:
    - key: argocd-app-health
  environments:
  - branch: environments/dev-us-central
  - branch: environments/int-us-central
    autoMerge: false
    # proposedCommitStatuses:
    # - key: promoter-previous-environment
  - branch: environments/prod-us-central
    autoMerge: false
    # proposedCommitStatuses:
    # - key: promoter-previous-environment
  gitRepositoryRef:
    name: git-repository-argo-promotion-test